ImageServiceWebApp/Controllers/ConfigurationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace ImageServiceWebApp.Models
{
    public class ConfigurationController : Controller
    {
        private static ConfigurationModel model = ConfigurationModel.Instance;

        public ConfigurationController() { }

        public ActionResult ConfigurationView()
        {
            return View(model);
        }

        public ActionResult DeleteConfirm(string toDelete)
        {
            model.NotifyRemoveHandler(toDelete);

            Thread.Sleep(1000);

            return RedirectToAction("ConfigurationView");
        }

        public ActionResult DeleteCancel()
        {
            return RedirectToAction("ConfigurationView");
        }
    }
}

ImageServiceWebApp/Controllers/ConfirmController.cs
using ImageServiceWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImageServiceWebApp.Controllers
{
    public class ConfirmController : Controller
    {
        private static ConfirmModel model = new ConfirmModel();

        public ConfirmController() { }

        public ActionResult ConfirmView()
        {
            return View(model);
        }

        public ActionResult DeleteHandler(string selectedHandler)
        {
            model.SelectedHandler = selectedHandler;
            return RedirectToAction("ConfirmView");
        }

        public ActionResult Delete()
        {
            return RedirectToAction("DeleteConfirm", "Configuration", new { toDelete = model.SelectedHandler });
        }

        public ActionResult Cancel()
        {
            return RedirectToAction("DeleteCancel", "Configuration");
        }
    }
}

ImageServiceWebApp/Views/Configuration/ConfigurationView.cshtml
@model ImageServiceWebApp.Models.ConfigurationModel

@{
    ViewBag.Title = "ConfigurationView";
}

<h2>Configuration Settings</h2>

<br/>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <table class="table">
            <tr>
                <td width="20%">
                    @Html.LabelFor(model => model.OutputDir)
                </td>
                <td>
                    @Html.DisplayFor(model => model.OutputDir)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.SourceName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.SourceName)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.LogName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.LogName)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.ThumbSize)
                </td>
                <td>
                    @Html.DisplayFor(model => model.ThumbSize)
                </td>
            </tr>

            <tr>
                <td>
                    @Html.LabelFor(model => model.Directories)
                </td>
                <td>
                    <table>
                        @foreach (var item in Model.Directories)
                        {
                            <tr>

                                <td>
                                    @Html.ActionLink(@item, "DeleteHandler", "Confirm", new { selectedHandler = item }, null)
                                </td>
                            </tr>
                        }
                    </table>

                </td>
            </tr>



        </table>


    </div>
}