ImageServiceWebApp/Controllers/ConfigurationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace ImageServiceWebApp.Models
{
    public class ConfigurationController : Controller
    {
        private static ConfigurationModel model = ConfigurationModel.Instance;

        public ConfigurationController() { }

        public ActionResult ConfigurationView()
        {
            return View(model);
        }

        public ActionResult DeleteConfirm(string toDelete)
        {
            model.NotifyRemoveHandler(toDelete);

            Thread.Sleep(1000);

            return RedirectToAction("ConfigurationView");
        }

        public ActionResult DeleteCancel()
        {
            return RedirectToAction("ConfigurationView");
        }
    }
}

ImageServiceWebApp/Controllers/LogController.cs
using ImageServiceWebApp.Models;
using ImageServiceWebApp.Models.Messages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImageServiceWebApp.Controllers
{
    public class LogController : Controller
    {
        private static LogModel model = LogModel.Instance;

        public LogController() { }

        public ActionResult LogView()
        {
            return View(model);
        }

        public void LogMessageUpdate(string type)
        {
            if (type != "")
            {
                model.SelectedLogMessages.Clear();
                foreach (LogMessage item in model.logMessages)
                {
                    if (item.Type == type)
                    {
                        model.AddToSelected(item);
                    }
                }
            }
            else
            {
                model.SelectedLogMessages.Clear();
            }
        }

        [HttpPost]
        public ActionResult LogChangeFilter(FormCollection form)
        {
            string type = form["typeFilter"].ToString();
            model.lastType = type;
            LogMessageUpdate(type);

            return RedirectToAction("LogView");
        }
    }
}

ImageServiceWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>

    <script src="~/Scripts/jquery-3.0.0.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Image Service Web Application", "HomeView", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "HomeView", "Home")</li>
                    <li>@Html.ActionLink("Config", "ConfigurationView", "Configuration")</li>
                    <li>@Html.ActionLink("Photos", "PhotosView", "Photos")</li>
                    <li>@Html.ActionLink("Logs", "LogView", "Log")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

</body>
</html>